/*
 * SYSTICK_Program.c
 *
 *  Created on: May 31, 2023
 *      Author: Mohamed Said
 */

#include "SYSTICK_Interface.h"
#include "SYSTICK_Private.h"
#include "SYSTICK_CNFG.h"
#include "BIT_MATH.h"
static void (*ptf)(void);

static u8 SYSTICK_SINGLE_PERIODIC_INT;


void MSYSTICK_VoidInit(void)
{
#if SYSTICK_CLOCK_SOURCE == SYSTICK_CLOCK_AHB
	SET_BIT(MSYSTICK_REG->CTRL,2);
#elif SYSTICK_CLOCK_SOURCE == SYSTICK_CLOCK_AHB_8
	CLR_BIT(MSYSTICK_REG->CTRL,2);
#endif
}
void MSYSTICK_VoidStopTimer(void)
{
	CLR_BIT(MSYSTICK_REG->CTRL,0);
}
void MSYSTICK_VoidSetBusyDelay(u32 Copy_U32LoadValue)
{
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	MSYSTICK_REG->VAL=0;
	CLR_BIT(MSYSTICK_REG->CTRL,1);
	SET_BIT(MSYSTICK_REG->CTRL,0);
	while (GET_BIT(MSYSTICK_REG->CTRL,16)==0);
	CLR_BIT(MSYSTICK_REG->CTRL,0);
}
void MSYSTICK_VoidSetIntervalSingle(u32 Copy_U32LoadValue)
{
	SYSTICK_SINGLE_PERIODIC_INT	=SYSTICK_SINGLE_INT;
	/*SETTING THE LOAD VALUE TO THE NUMBER OF PROCESSOR CYCLES WE WANT*/
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	/*CLEARING THE VALUE REGISTER AND THE COUNTR FLAG*/
	MSYSTICK_REG->VAL=0;
	/*SETTING THE INTERRUPT ENABLE*/
	SET_BIT(MSYSTICK_REG->CTRL,1);
	/*ENABLE THE COUNTER TO START COUNTING*/
	SET_BIT(MSYSTICK_REG->CTRL,0);
}
void MSYSTICK_VoidSetIntervalPerodic(u32 Copy_U32LoadValue)
{
	SYSTICK_SINGLE_PERIODIC_INT	=SYSTICK_PERODIC_INT;
	/*SETTING THE LOAD VALUE TO THE NUMBER OF PROCESSOR CYCLES WE WANT*/
	MSYSTICK_REG->LOAD=Copy_U32LoadValue;
	/*CLEARING THE VALUE REGISTER AND THE COUNTR FLAG*/
	MSYSTICK_REG->VAL=0;
	/*SETTING THE INTERRUPT ENABLE*/
	SET_BIT(MSYSTICK_REG->CTRL,1);
	/*ENABLE THE COUNTER TO START COUNTING*/
	SET_BIT(MSYSTICK_REG->CTRL,0);
}
u32  MSYSTICK_U32GetElabsedTimer(void)
{
	return MSYSTICK_REG->LOAD-MSYSTICK_REG->VAL;
}
u32  MSYSTICK_U32GetRemainingTime(void)
{
	return MSYSTICK_REG->VAL;
}
void MSYSTICK_VoidSetCallBack(void (*ptr)(void))
{
	ptf=ptr;
}

void SysTick_Handler(void)
{
	if(SYSTICK_SINGLE_PERIODIC_INT==SYSTICK_SINGLE_INT)
	{
		/*stop timer*/
		CLR_BIT(MSYSTICK_REG->CTRL,0);
	}
	ptf();
	/*CLEAR INTERRUPT FLAG*/
	GET_BIT(MSYSTICK_REG->CTRL,16);
}
